let pilhamax=
[
{"id":40,"direcao":"esq"},{"id":41,"direcao":"baixo"},
{"id":23,"direcao":"baixo"},{"id":5,"direcao":"dir"},
{"id":32,"direcao":"esq"},{"id":14,"direcao":"cima"},
{"id":23,"direcao":"baixo"},{"id":14,"direcao":"dir"},
{"id":32,"direcao":"baixo"},{"id":34,"direcao":"cima"},
{"id":33,"direcao":"esq"},{"id":35,"direcao":"cima"},
{"id":34,"direcao":"dir"},{"id":33,"direcao":"esq"},
{"id":32,"direcao":"dir"},{"id":23,"direcao":"dir"},
{"id":31,"direcao":"esq"},{"id":32,"direcao":"cima"},
{"id":41,"direcao":"baixo"},{"id":30,"direcao":"cima"},
{"id":32,"direcao":"dir"},{"id":50,"direcao":"baixo"},
{"id":48,"direcao":"esq"},{"id":50,"direcao":"cima"},
{"id":68,"direcao":"dir"},{"id":59,"direcao":"cima"},
{"id":77,"direcao":"dir"},{"id":68,"direcao":"baixo"},
{"id":30,"direcao":"dir"},{"id":28,"direcao":"cima"},
{"id":29,"direcao":"dir"},{"id":31,"direcao":"dir"},
{"id":49,"direcao":"baixo"},{"id":39,"direcao":"cima"},
{"id":59,"direcao":"cima"},{"id":57,"direcao":"esq"},
{"id":37,"direcao":"esq"},{"id":38,"direcao":"dir"},
{"id":29,"direcao":"cima"}
]


let bb = 
[{id: 40, direcao: 'esq'},
 {id: 41, direcao: 'baixo'},
 {id: 23, direcao: 'baixo'},
 {id: 5, direcao: 'dir'},
 {id: 32, direcao: 'cima'},
 {id: 14, direcao: 'cima'},
 {id: 23, direcao: 'baixo'},
 {id: 14, direcao: 'dir'},
 {id: 32, direcao: 'baixo'},
 {id: 23, direcao: 'dir'},
 {id: 41, direcao: 'baixo'},
 {id: 32, direcao: 'esq'},
 {id: 34, direcao: 'cima'},
 {id: 33, direcao: 'esq'},
 {id: 35, direcao: 'cima'},
 {id: 34, direcao: 'dir'},
 {id: 33, direcao: 'esq'},
 {id: 32, direcao: 'dir'},
 {id: 31, direcao: 'esq'},
 {id: 42, direcao: 'dir'},
 {id: 33, direcao: 'cima'},
 {id: 30, direcao: 'dir'},
 {id: 32, direcao: 'dir'},
 {id: 31, direcao: 'esq'},
 {id: 40, direcao: 'cima'},
 {id: 49, direcao: 'baixo'},
 {id: 28, direcao: 'cima'},
 {id: 29, direcao: 'dir'},
 {id: 27, direcao: 'cima'},
 {id: 30, direcao: 'cima'},
 {id: 28, direcao: 'esq'},
 {id: 29, direcao: 'dir'},
 {id: 48, direcao: 'cima'},
 {id: 46, direcao: 'esq'},
 {id: 47, direcao: 'baixo'},
 {id: 48, direcao: 'dir'},
 {id: 50, direcao: 'dir'},
 {id: 41, direcao: 'cima'},
 {id: 66, direcao: 'esq'},
 {id: 57, direcao: 'cima'},
 {id: 75, direcao: 'esq'}]